[Re: e2nguyen/Watcher#21]
e2nguyen/Watcher pull request #30
Opened 2020-12-26 20:22 UTC by dianephan

2021-01-16 19:55 UTC, e2nguyen requested changes
Let's remove the node_modules directory and yarn and .next files/directories.

2021-01-16 19:55 UTC, e2nguyen commented on components/button/button.tsx
> +import React, { Children } from "react";
can we remove this `{ Children }` bit from line 1 since it's not being used anywhere?

2021-01-16 19:55 UTC, e2nguyen commented on components/button/button.tsx
> +  onClick: () => void;
nitpicky, but let's alphabetize these props

2021-01-16 19:55 UTC, e2nguyen commented on components/button/button.tsx
> +  onClick
let's also alphabetize the props here

2021-01-16 19:55 UTC, e2nguyen commented on components/button/button.tsx
> +    <div className="container">
let's rename this to be `custom-button-container` to be more specific because i imagine we'll be having lots on containerized components

2021-01-16 19:55 UTC, e2nguyen commented on components/button/button.tsx
> +        className="firstbutton-check"
Can we rename this className to something else? I'm not sure what firstbutton-check really means. Maybe we could aim for something along the lines on indicating it's the actually csutom button element like `custom-button`.

2021-01-16 19:55 UTC, e2nguyen commented on components/button/button.tsx
> +        .firstbutton-check {
let's rename the className here too to match

2021-01-16 19:55 UTC, e2nguyen commented on components/button/button.tsx
> +          background-image: url(${backgroundURL});
let's alphabetize these styles

2021-01-16 21:23 UTC, dianephan commented
Ugh, I tried to git rm -rf the node_modules, .next, and yarn.lock files/directories and I guess that's why 5000+ changes were made... sorry. I ran the following:

`git add components/button/button.tsx`
`git add pages/components-playground.tsx`

because those were essentially the only 2 files I made changes to and want to commit

2021-01-31 18:32 UTC, e2nguyen approved these changes
lgtm! nice work removing all the clutter

2021-01-31 18:33 UTC, merged